### ISSUE TITLE
build-push-image gh workflow is not caching

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/osm-tagger#32]
I noticed the build taking a long time on a PR that doesnt touch the dockerfiles: https://github.com/hotosm/osm-tagger/actions/runs/14937770141/job/41969154296?pr=31

This doesn't use the [resusable workflow](https://hotosm.github.io/gh-workflows/image_build/), which caches by default. Consider switching to using the reusable workflow, or enable caching manually.

**Comment by spwoodcock** [comment]
This should use our re-usable workflow, like so:

```yaml
  backend-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.4.2
    with:
      context: src
      dockerfile: dockerfiles/app.dockerfile
      build_target: runtime
      image_name: ghcr.io/${{ github.repository }}/osm-tagger
```

This will do multi-arch, nicely tagged, and cached builds.
